name: macos python build
on: [push, pull_request]

jobs:
  macos-build:
    name: Dub build
    strategy:
      matrix:
        os: [macos-latest]
        dc: [ldc-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Install htslib deps
        run: |
            brew install xz autoconf automake
      - name: Get dhtslib commit
        id: get-dhtslib-commit
        run: echo "::set-output name=sha_short::$(git rev-parse --short :dhtslib)"

      - name: Cache dhtslib
        id: cache-dhtslib
        uses: actions/cache@v2
        with:
          path: dhtslib
          key: ${{ runner.os}}-dhtslib-${{ steps.get-dhtslib-commit.outputs.sha_short }}

      - name: Build htslib
        if: steps.cache-dhtslib.outputs.cache-hit != 'true'
        run: |
            cd dhtslib/htslib
            autoreconf -i
            ./configure
            make
      - name: Install htslib
        run: |
            cd dhtslib/htslib
            sudo make install
      - name: Setup additional test files
        run: |
            cd dhtslib/htslib
            cd test
            cd tabix
            bgzip -c gff_file.gff > gff_file.gff.gz
            tabix gff_file.gff.gz
            bgzip -c bed_file.bed > bed_file.bed.gz
            tabix bed_file.bed.gz
            bgzip -c vcf_file.vcf > vcf_file.vcf.gz
            tabix vcf_file.vcf.gz
      - name: Install python deps
        run: |
            python -m pip install --upgrade pip
            pip install cython pyd
      - name: Run tests
        run: |
            python setup.py build -c ldc
            python setup.py install
            python -c "import recontig"
        env:
          LIBRARY_PATH: /usr/local/lib

      # - name: Upload coverage
        # run: bash <(curl -s https://codecov.io/bash)